#!/bin/ksh

# 21 December 2011 Matt Warner
# First-boot script for Solaris 11 systems
# where the SST is run while the system is still being built
# with AI (replacement for JumpStart). If the system is already
# booted into normal, multi-user mode (i.e. not JumpStart), you 
# should not need this script since SST should be applying these
# settings already!
#
# With special thanks to Steffen Weiberle for taking the time to document
# http://blogs.oracle.com/stw/entry/solaris_11_express_network_tunables
#
# Other useful reference: 
# http://docs.oracle.com/cd/E23824_01/html/821-1450/appendixa-28.html

LOCATION=`dirname $0`
SCRIPTNAME=`basename $0`

logger info "Running first boot script from $LOCATION/$SCRIPTNAME"

# $1 = prop name
# $2 = protocol
# $3 = value to append
append_value() {
 echo "Appending $3 to $CURR_VAL for $2 $1"
 echo ipadm set-prop -p $1+="$3" $2
 ipadm set-prop -p $1+="$3" $2
}

# overwrite values
# $1 = prop name
# $2 = protocol
# $3 = value to set
set_value() {
 echo "setting $1 to $3 for $2"
 echo ipadm set-prop -p $1="$3" $2
 ipadm set-prop -p $1="$3" $2
}

# eliminate all values
# $1 = prop name
# $2 = protocol
eliminate_values() {
 # First set a bogus value
 # and then delete it
 # this might not work for all protocol/property combinations...
 echo "Attempting to set value of 1 for property $1 protocol $2"
 ipadm set-prop -p $1="1" $2
 # Now subtract out the value we just set
 echo "Attempting to subtract out the 1 for property $1 protocol $2"
 ipadm set-prop -p $1-="1" $2
}

# First ndd settings
append_value extra_priv_ports tcp 6112
eliminate_values extra_priv_ports udp 
set_value _forward_directed_broadcasts ip 0
set_value _rev_src_routes tcp 0
set_value _conn_req_max_q0 tcp 4096
set_value _conn_req_max_q tcp 1024
set_value smallest_anon_port tcp 32768
set_value smallest_anon_port udp 32768
set_value largest_anon_port tcp 65535
set_value largest_anon_port udp 65535
set_value smallest_nonpriv_port tcp 1024
set_value smallest_nonpriv_port udp 1024
set_value _respond_to_echo_broadcast ip 0
set_value _respond_to_echo_multicast ipv4 0
set_value _respond_to_echo_multicast ipv6 0
set_value _respond_to_timestamp ip 0
set_value _respond_to_timestamp_broadcast ip 0
set_value _respond_to_address_mask_broadcast ip 0
set_value _ignore_redirect ipv4 0
set_value _ignore_redirect ipv6 0
set_value _forward_src_routed ipv4 0
set_value _forward_src_routed ipv6 0
set_value _send_redirects ipv4 0
set_value _send_redirects ipv6 0
set_value ttl ipv4 255
set_value hoplimit ipv6 255
set_value hostmodel ipv4 strong
set_value hostmodel ipv6 strong
set_value forwarding ipv4 off
set_value forwarding ipv6 off

# there's not need to run it every time since Solaris 11 keeps
# the settings
rm $LOCATION/$SCRIPTNAME
