#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the License).
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/CDDL.txt
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/CDDL.txt.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets [] replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident  "@(#)swapadd 1.2     04/03/16     SMI"
#
# This script is added by the Sun Security Toolkit: Community Edition Finish script:
# disable-nfs-client.fin.  This is done to ensure that swap files
# defined in /etc/vfstab are added on system boot.  This script has
# been added to replace functionality typically implemented by 
# /etc/rc2/S73nfs.client (which has been disabled by the Toolkit
# Finish script, disable-nfs-client.fin).
#

returnValue=0

case "$1" in
   'start')
      # Only do this for 'start' operations.
      /sbin/swapadd
      returnValue=$?
      ;;

esac

exit ${returnValue} 
