#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the License).
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/CDDL.txt
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/CDDL.txt.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets [] replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)preremove	1.1	05/06/08 SMI"

#
# Exit with error if any files have been changed by the customer
#

PKGCHK="/usr/sbin/pkgchk"
AWK="/bin/awk"

TMPOUT="/tmp/SUNWsst.preremove.$$"

if [ -x ${PKGCHK} ] ; then
	${PKGCHK} ${PKG} 1> ${TMPOUT} 2>&1
	TMPVAL=$?
	# ${PKGCHK} exits non-zero when a file's checksum does not match
	# or if file missing or if modtime change
	if [ ${TMPVAL} -ne 0 ] ; then
		# Make a list of only changed files
		MODFILES=` ${AWK} '{ 
			{ if ( $1 == "ERROR:" ) { TMPNAME = $2 ; } }
			{ if ( $2 == "cksum" ) { print TMPNAME ; } }
			}' ${TMPOUT} `
		rm -f ${TMPOUT}
		if [ "${MODFILES}" != "" ] ; then
			# Print error message and list the files.
			echo "ERROR: The following files have been changed"
			echo "	since the ${PKG} package was installed."
			echo "	You must remove, rename or restore these files"
			echo "	before you can remove the ${PKG} package."
			for x in ${MODFILES} ; do
				echo "	${x}"
			done
			exit 1
		fi
	fi
fi

exit 0
